name: college_master
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_indicators: ^0.1.5
  multiselect_formfield: ^0.1.4
  flag: ^3.0.5
  location: ^3.0.2
  url_launcher: ^5.4.2
  file_picker: ^1.4.3+1
  firebase_core: "^0.5.0"
  cloud_firestore: "^0.14.1+1"
  image_picker: ^0.6.0+17
  image_cropper: 1.0.2
  firebase_storage: ^4.0.1
  google_maps_flutter: ^1.0.2
  flutter_launcher_icons: "^0.8.0"
  font_awesome_flutter: ^8.8.1
  fluttericon: ^1.0.7
  slimy_card: ^1.0.4
  intl: ^0.16.1
  calendar_timeline: ^0.6.3
  flutter_swiper: ^1.1.6
  smooth_star_rating: ^1.1.1
  flappy_search_bar: ^1.4.1
  fluster: ^1.1.2
  charts_flutter: ^0.9.0
  direct_select: "^1.0.3"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path_ios: "images/gradhat.png"
  image_path_android: "images/gradhat.png"

flutter_native_splash:
  image: "images/gradhat.png"
  color: "68c1e7"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/user.png
    - images/gradhat.png
    - images/sample_logo.png
    - images/pranav.png
    - images/sasi.png
    - images/hemang.png
    - images/aman.png
    - images/India.png
    - images/georgiatech.jpg
    - images/georgiatech_logo.jpg
    - images/georgia_tech_1.png
    - images/georgia_tech_2.jpg
    - images/georgia_tech_3.png
    - images/georgia_tech_4.jpg
    - images/georgia_tech_5.jpg
    - images/georgia_tech_startup_1.jpg
    - images/georgia_tech_startup_2.jpg
    - images/georgia_tech_startup_3.png
    - images/georgia_tech_startup_4.png
    - images/georgia_tech_company_1.jpg
    - images/georgia_tech_company_2.jpg
    - images/georgia_tech_company_3.png
    - images/georgia_tech_company_4.jpg
    - images/georgia_tech_company_5.png
    - images/earth.png
    - images/Logo_png.png
    - images/gates.png
    - images/musk.png
    - images/jobs.png
    - images/helen.png
    - images/logo2.png
    - images/georgiatech.png
    - images/warwick.png
    - images/oxford.png
    - images/harvard.png
    - images/imperial.png
    - images/tedx.svg.png
    - images/commonapp.svg.png
    - images/image1.png
    - images/image2.png
    - images/image3.png
    - images/image4.png
    - images/image5.png
    - images/image6.png
    - images/image7.png
    - images/image8.png
    - images/image9.png
    - images/image10.png
    - images/image11.png
    - images/image12.png
    - images/image13.png
    - images/image14.png
    - images/image15.png
    - images/image16.png
    - images/image17.png
    - images/image18.png
    - images/image19.png
    - images/image20.png
    - images/image21.png
    - images/image22.png
    - images/image23.png
    - images/image24.png
    - images/image25.png
    - images/image26.png
    - images/image27.png
    - images/image28.png
    - images/image29.png
    - images/image30.png
    - images/marker.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
